trigger:
- '*'
pr:
- '*'

jobs:
- job: Build
  displayName: 'Build job'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      # Install OpenJDK 11
      sudo apt-get install openjdk-11-jdk -y

      # Build the Spring Boot application using Maven
      ./mvnw clean package -DskipTests=true
    displayName: 'Build'
    workingDirectory: $(System.DefaultWorkingDirectory)

- job: Test
  displayName: 'Test job'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Build
  steps:
  - script: |
      # Run tests using Maven
      ./mvnw test
    displayName: 'Run Tests'
    workingDirectory: $(System.DefaultWorkingDirectory)

- job: Publish
  displayName: 'Publish Artifacts'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Test
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      artifactName: 'drop'
    displayName: 'Publish Artifact'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Publish
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      # Install Azure CLI extension for webapps
      pip install --upgrade azure-cli
      az extension add --name webapp

      # Azure login (replace with your Azure service connection)
      az login --service-principal -u <service-principal-id> -p <service-principal-password> --tenant <tenant-id>

      # Deploy the Spring Boot JAR to Azure App Service (replace with your specific details)
      az webapp deploy --name <app-service-name> --resource-group <resource-group-name> --type jar --path '$(System.DefaultWorkingDirectory)/target/abc.jar'
    displayName: 'Deploy to Azure App Service'
